import {auth,db,onAuthStateChanged,signInWithEmailAndPassword,signOut,collection,doc,getDocs,getDoc,setDoc,addDoc,updateDoc,deleteDoc,query,orderBy,serverTimestamp} from './firebase.js';
const $=id=>document.getElementById(id);
let rounds=[],teams=[],settings={schoolName:'OM SHANTI ACADEMY',competitionTitle:'INTER-HOUSE SPELLING BEE COMPETITION - 2083',schoolLocation:'Bharatpur 10, Chitwan',pageSize:10};
let selectedRound='';
function msg(el,text,ok=false){$(el).textContent=text;$(el).className='feedback '+(ok?'correct':'wrong');}
async function ensureAdmin(user){const token=await user.getIdTokenResult(true); if(token.claims.admin!==true){await signOut(auth); throw new Error('This account is not marked as an admin. Set the admin custom claim in Firebase Admin SDK.');}}
async function loadAll(){
 const rs=await getDocs(query(collection(db,'rounds'),orderBy('order'))); rounds=rs.docs.map(d=>({id:d.id,...d.data()}));
 const ts=await getDocs(query(collection(db,'teams'),orderBy('order'))); teams=ts.docs.map(d=>({id:d.id,...d.data()}));
 const s=await getDoc(doc(db,'competition','settings')); if(s.exists()) settings={...settings,...s.data()};
 selectedRound=selectedRound||rounds[0]?.id||''; renderAll();
}
function renderAll(){
 $('statRounds').textContent=rounds.length; $('statTeams').textContent=teams.length;
 Promise.all(rounds.map(r=>getDocs(collection(db,'rounds',r.id,'questions')))).then(xs=>$('statQuestions').textContent=xs.reduce((n,s)=>n+s.size,0));
 renderRounds();renderQuestions();renderTeams();renderSettings();
}
function renderRounds(){ $('roundList').innerHTML=rounds.map(r=>`<div class="manage-row"><div><b>${esc(r.name)}</b><small>${r.questionCount||0} questions</small></div><div class="row-actions"><button data-open="${r.id}" class="secondary-btn small">Open</button><button data-edit="${r.id}" class="secondary-btn small">Edit</button><button data-del="${r.id}" class="danger-btn small">Delete</button></div></div>`).join('')||empty('No rounds yet.'); document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.href='round.html?round='+b.dataset.open); document.querySelectorAll('[data-edit]').forEach(b=>editRound(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>deleteRound(b.dataset.del));}
function renderQuestions(){const sel=$('questionRoundFilter');sel.innerHTML=rounds.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');if(selectedRound)sel.value=selectedRound; sel.onchange=()=>{selectedRound=sel.value;renderQuestions();}; const list=$('questionList'); if(!selectedRound){list.innerHTML=empty('Create a round first.');return;} getDocs(query(collection(db,'rounds',selectedRound,'questions'),orderBy('order'))).then(s=>{list.innerHTML=s.docs.map(d=>{const q=d.data();return `<div class="manage-row"><div><b>Q${q.order}: ${esc(q.prompt||'Spell the word')}</b><small>Answer: ${esc(q.word)} • ${q.points||10} pts</small></div><div class="row-actions"><button class="secondary-btn small" data-qedit="${d.id}">Edit</button><button class="danger-btn small" data-qdel="${d.id}">Delete</button></div></div>`}).join('')||empty('No questions in this round.');list.querySelectorAll('[data-qedit]').forEach(b=>editQuestion(b.dataset.qedit));list.querySelectorAll('[data-qdel]').forEach(b=>deleteQuestion(b.dataset.qdel));});}
function renderTeams(){$('teamList').innerHTML=teams.map(t=>`<div class="team-row"><input data-team-name="${t.id}" value="${esc(t.name)}"><button class="secondary-btn small" data-team-save="${t.id}">Save</button><button class="danger-btn small" data-team-del="${t.id}">Delete</button></div>`).join('')||empty('No teams yet.');document.querySelectorAll('[data-team-save]').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'teams',b.dataset.teamSave),{name:$(`[data-team-name="${b.dataset.teamSave}"]`).value.trim()});loadAll();});document.querySelectorAll('[data-team-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this team?')){await deleteDoc(doc(db,'teams',b.dataset.teamDel));loadAll();}});}
function renderSettings(){$('schoolName').value=settings.schoolName;$('competitionTitle').value=settings.competitionTitle;$('schoolLocation').value=settings.schoolLocation;$('pageSize').value=settings.pageSize||10;}
async function addRound(){const name=prompt('Round name','Round '+(rounds.length+1));if(!name)return;const order=rounds.length+1;const ref=await addDoc(collection(db,'rounds'),{name,order,active:true,createdAt:serverTimestamp()});selectedRound=ref.id;await loadAll();}
async function editRound(id){const r=rounds.find(x=>x.id===id);const name=prompt('Round name',r.name);if(name&&name!==r.name){await updateDoc(doc(db,'rounds',id),{name});loadAll();}}
async function deleteRound(id){if(!confirm('Delete this round and all its questions?'))return;const qs=await getDocs(collection(db,'rounds',id,'questions'));const batch=(await import('./firebase.js')).writeBatch(db);qs.forEach(d=>batch.delete(d.ref));batch.delete(doc(db,'rounds',id));await batch.commit();loadAll();}
async function addQuestion(){if(!selectedRound)return;const word=prompt('Correct spelling / answer');if(!word)return;const promptText=prompt('Prompt or definition (optional)','Spell the word you hear.');const points=Number(prompt('Points','10'))||10;const qs=await getDocs(collection(db,'rounds',selectedRound,'questions'));await addDoc(collection(db,'rounds',selectedRound,'questions'),{order:qs.size+1,word:word.trim(),prompt:promptText||'Spell the word you hear.',points,hint:'',createdAt:serverTimestamp()});await updateDoc(doc(db,'rounds',selectedRound),{questionCount:qs.size+1});loadAll();}
async function editQuestion(id){const ref=doc(db,'rounds',selectedRound,'questions',id);const s=await getDoc(ref);if(!s.exists())return;const q=s.data();const word=prompt('Correct spelling / answer',q.word);if(!word)return;const promptText=prompt('Prompt / definition',q.prompt||'');const points=Number(prompt('Points',q.points||10))||10;await updateDoc(ref,{word:word.trim(),prompt:promptText||'',points});renderQuestions();}
async function deleteQuestion(id){if(!confirm('Delete this question?'))return;await deleteDoc(doc(db,'rounds',selectedRound,'questions',id));const qs=await getDocs(query(collection(db,'rounds',selectedRound,'questions'),orderBy('order')));let i=1;for(const d of qs.docs){await updateDoc(d.ref,{order:i++});}await updateDoc(doc(db,'rounds',selectedRound),{questionCount:qs.size});renderQuestions();renderAll();}
async function addTeam(){const name=prompt('Team / house name','Team '+String.fromCharCode(65+teams.length));if(!name)return;await addDoc(collection(db,'teams'),{name:name.trim(),order:teams.length+1,score:0});loadAll();}
async function saveSettings(){settings={schoolName:$('schoolName').value.trim(),competitionTitle:$('competitionTitle').value.trim(),schoolLocation:$('schoolLocation').value.trim(),pageSize:Math.max(5,Math.min(20,Number($('pageSize').value)||10))};await setDoc(doc(db,'competition','settings'),settings,{merge:true});msg('settingsMsg','Settings saved.',true);}
function empty(t){return `<div class="empty-manage">${t}</div>`}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('loginEmail').value,$('loginPassword').value);}catch(e){msg('loginMsg',e.message);}};
$('logoutBtn').onclick=()=>signOut(auth);
$('addRound').onclick=addRound;$('quickRound').onclick=addRound;$('addQuestion').onclick=addQuestion;$('quickQuestion').onclick=()=>{document.querySelector('[data-panel="questions"]').click();addQuestion();};$('addTeam').onclick=addTeam;$('saveSettings').onclick=saveSettings;
document.querySelectorAll('.admin-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-panel').forEach(p=>p.hidden=p.dataset.content!==b.dataset.panel);if(b.dataset.panel==='questions')renderQuestions();});
onAuthStateChanged(auth,async user=>{if(!user){$('loginView').hidden=false;$('adminView').hidden=true;$('logoutBtn').hidden=true;return;}try{await ensureAdmin(user);$('loginView').hidden=true;$('adminView').hidden=false;$('logoutBtn').hidden=false;await loadAll();}catch(e){$('loginView').hidden=false;$('adminView').hidden=true;msg('loginMsg',e.message);}});
