import {auth,db,onAuthStateChanged,signOut,collection,doc,getDocs,getDoc,updateDoc,addDoc,query,orderBy,onSnapshot} from './firebase.js';
let rounds=[],teams=[],selectedIndex=0,roundId=new URLSearchParams(location.search).get('round')||'';let currentQuestions=[];const $=id=>document.getElementById(id);
function label(s){return ({pending:'Not attempted',correct:'Correct',passed:'Passed',ended:'Turn ended',revealed:'Answer revealed'})[s]||s||'Not attempted';}
async function load(){const r=await getDoc(doc(db,'rounds',roundId));if(!r.exists()){alert('Round not found');location.href='admin.html';return;} $('roundTitle').textContent=r.data().name;const ts=await getDocs(query(collection(db,'teams'),orderBy('order')));teams=ts.docs.map(d=>({id:d.id,...d.data()}));$('teamSelect').innerHTML=teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');subscribeQuestions();}
function subscribeQuestions(){onSnapshot(query(collection(db,'rounds',roundId,'questions'),orderBy('order')),snap=>{currentQuestions=snap.docs.map(d=>({id:d.id,...d.data()}));if(selectedIndex>=currentQuestions.length)selectedIndex=Math.max(0,currentQuestions.length-1);renderTabs();renderQuestion();});}
function renderTabs(){const page=Number(localStorage.getItem('qPage')||0),size=10;const start=page*size;const visible=currentQuestions.slice(start,start+size);$('questionTabs').innerHTML=visible.map((q,i)=>`<button class="question-tab ${q.status&&q.status!=='pending'?'done ':''}${start+i===selectedIndex?'active':''}" data-i="${start+i}">${q.order}</button>`).join('');document.querySelectorAll('.question-tab').forEach(b=>b.onclick=()=>{selectedIndex=Number(b.dataset.i);renderTabs();renderQuestion();});$('qPrev').disabled=page===0;$('qNext').disabled=start+size>=currentQuestions.length;$('qPrev').onclick=()=>{localStorage.setItem('qPage',Math.max(0,page-1));selectedIndex=Math.max(0,(page-1)*size);renderTabs();renderQuestion();};$('qNext').onclick=()=>{localStorage.setItem('qPage',page+1);selectedIndex=page*size+size;renderTabs();renderQuestion();};}
function renderQuestion(){const q=currentQuestions[selectedIndex];if(!q){$('wordPrompt').textContent='No questions yet';return;}$('questionLabel').textContent=`Question ${q.order} • ${q.points||10} points`;$('wordPrompt').textContent=q.prompt||'Spell the word you hear.';$('wordHint').textContent=q.hint||'Enter the contestant spelling below.';$('spellInput').value='';$('feedback').textContent='';$('feedback').className='feedback';$('answerPanel').hidden=q.status!=='revealed';$('answerText').textContent=q.word||'';$('statusPill').textContent=label(q.status);$('statusPill').className='status-pill '+(q.status||'');}
async function setStatus(status,feedback){const q=currentQuestions[selectedIndex];if(!q)return;const teamId=$('teamSelect').value;await updateDoc(doc(db,'rounds',roundId,'questions',q.id),{status,lastTeamId:teamId,lastUpdatedAt:new Date()});if(status==='correct')await updateTeamScore(teamId,Number(q.points||10));$('feedback').textContent=feedback||'';$('feedback').className='feedback '+(status==='correct'?'correct':'wrong');if(status==='revealed'){ $('answerPanel').hidden=false; $('answerText').textContent=q.word; }}
async function updateTeamScore(teamId,delta){const t=teams.find(x=>x.id===teamId);if(!t)return;await updateDoc(doc(db,'teams',teamId),{score:Number(t.score||0)+delta});}
$('checkBtn').onclick=async()=>{const q=currentQuestions[selectedIndex],v=$('spellInput').value.trim();if(!v){$('feedback').textContent='Enter a spelling first.';return;}if(v.toLowerCase()===q.word.toLowerCase())await setStatus('correct','✓ Correct spelling!');else await setStatus('ended','✗ Not correct. Reveal the answer or move on.');renderQuestion();};$('spellInput').onkeydown=e=>{if(e.key==='Enter')$('checkBtn').click();};$('passBtn').onclick=()=>setStatus('passed','Turn passed.');$('endBtn').onclick=()=>setStatus('ended','Turn ended.');$('revealBtn').onclick=()=>setStatus('revealed','Answer revealed.');$('prevQuestion').onclick=()=>{if(selectedIndex>0){selectedIndex--;renderTabs();renderQuestion();}};$('nextQuestion').onclick=()=>{if(selectedIndex<currentQuestions.length-1){selectedIndex++;renderTabs();renderQuestion();}};$('addTeam').onclick=async()=>{const name=prompt('Team / house name');if(!name)return;const ref=await addDoc(collection(db,'teams'),{name:name.trim(),order:teams.length+1,score:0});$('teamSelect').innerHTML+=`<option value="${ref.id}">${esc(name.trim())}</option>`;};function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
onAuthStateChanged(auth,async user=>{if(!user){location.href='admin.html';return;}const token=await user.getIdTokenResult(true);if(token.claims.admin!==true){await signOut(auth);location.href='admin.html';return;}load();});
